version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - 27017:27017
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin